apiVersion: v1
kind: LimitRange
metadata:
  name: jenkins-limitrange
  namespace: my-jenkins  # namespace which is created
spec:
  limits:
    - default:
        cpu: "0.4"
        memory: 500Mi
      defaultRequest:
        cpu: "0.4"
        memory: 250Mi
      type: Container
	 
