apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: jenkins-replicaset
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: jenkins-deployment
  template:
    metadata:
      labels:
        app: jenkins-deployment
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:latest
          ports:
            - containerPort: 8080
          # Uncomment if tolerations needed
          # tolerations:
          #   - key: name
          #     operator: "Equal"
          #     value: "qa"
          #     effect: "NoExecute"
          # Uncomment if nodeSelector needed
          # nodeSelector:
          #   colour: red
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 5
              preference:
                matchExpressions:
                  - key: colour
                    operator: In
                    values:
                      - pink
